services:
  postgres:
    image: postgres:16-alpine
    container_name: sycamore_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sycamore_user
      POSTGRES_PASSWORD: sycamore_pass
      POSTGRES_DB: sycamore_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
